// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {catalog} from '../models';

export function GenerateVariants(arg1:Array<string>,arg2:Array<string>):Promise<Array<engine.Variant>>;

export function ListChampions():Promise<Array<catalog.Champion>>;
