// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateVariants(arg1, arg2) {
  return window['go']['main']['App']['GenerateVariants'](arg1, arg2);
}

export function ListChampions() {
  return window['go']['main']['App']['ListChampions']();
}
